spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=TRUE&allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: rootroot
logging:
  level:
    root: info
    com.example.mybatisexample.mapper: error
server:
  port: 8082
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
